NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.importer.bridgelabz.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.importer.bridgelabz.com-cert.pem
    OrganizationalUnitIdentifier: peer
