NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.exporter.bridgelabz.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.exporter.bridgelabz.com-cert.pem
    OrganizationalUnitIdentifier: peer
